package com.example.quiniela_virtual_app.presentation.shared

internal val NOMBRES_ES: Map<String, String> = mapOf(
    // Asia
    "Korea Republic"         to "Corea del Sur",
    "Korea DPR"              to "Corea del Norte",
    "IR Iran"                to "Irán",
    "Saudi Arabia"           to "Arabia Saudita",
    "Japan"                  to "Japón",
    "China PR"               to "China",
    "Uzbekistan"             to "Uzbekistán",
    "Indonesia"              to "Indonesia",
    "Jordan"                 to "Jordania",
    "Iraq"                   to "Irak",
    "Bahrain"                to "Baréin",
    "Oman"                   to "Omán",
    "Qatar"                  to "Catar",
    "United Arab Emirates"   to "Emiratos Árabes Unidos",
    "Syria"                  to "Siria",
    "Lebanon"                to "Líbano",
    "Palestine"              to "Palestina",
    "Thailand"               to "Tailandia",
    "Philippines"            to "Filipinas",
    "Malaysia"               to "Malasia",
    "Kazakhstan"             to "Kazajistán",
    "Kyrgyzstan"             to "Kirguistán",
    "Tajikistan"             to "Tayikistán",
    "Turkmenistan"           to "Turkmenistán",
    // África
    "South Africa"           to "Sudáfrica",
    "Morocco"                to "Marruecos",
    "Cameroon"               to "Camerún",
    "Egypt"                  to "Egipto",
    "Côte d'Ivoire"          to "Costa de Marfil",
    "DR Congo"               to "Congo RD",
    "Algeria"                to "Argelia",
    "Tunisia"                to "Túnez",
    "Nigeria"                to "Nigeria",
    "Senegal"                to "Senegal",
    "Ghana"                  to "Ghana",
    "Mali"                   to "Mali",
    "Cape Verde"             to "Cabo Verde",
    "Kenya"                  to "Kenia",
    "Ethiopia"               to "Etiopía",
    "Libya"                  to "Libia",
    "Zimbabwe"               to "Zimbabue",
    "Sudan"                  to "Sudán",
    "Benin"                  to "Benín",
    // Europa
    "Germany"                to "Alemania",
    "France"                 to "Francia",
    "Spain"                  to "España",
    "Italy"                  to "Italia",
    "Netherlands"            to "Países Bajos",
    "Belgium"                to "Bélgica",
    "Croatia"                to "Croacia",
    "England"                to "Inglaterra",
    "Serbia"                 to "Serbia",
    "Switzerland"            to "Suiza",
    "Denmark"                to "Dinamarca",
    "Austria"                to "Austria",
    "Scotland"               to "Escocia",
    "Romania"                to "Rumanía",
    "Slovakia"               to "Eslovaquia",
    "Hungary"                to "Hungría",
    "Czechia"                to "República Checa",
    "Czech Republic"         to "República Checa",
    "Poland"                 to "Polonia",
    "Slovenia"               to "Eslovenia",
    "Türkiye"                to "Turquía",
    "Turkey"                 to "Turquía",
    "Ukraine"                to "Ucrania",
    "Greece"                 to "Grecia",
    "Wales"                  to "Gales",
    "Sweden"                 to "Suecia",
    "Norway"                 to "Noruega",
    "Finland"                to "Finlandia",
    "Russia"                 to "Rusia",
    "Iceland"                to "Islandia",
    "Ireland"                to "Irlanda",
    "Northern Ireland"       to "Irlanda del Norte",
    "North Macedonia"        to "Macedonia del Norte",
    "Bosnia and Herzegovina" to "Bosnia y Herzegovina",
    "Luxembourg"             to "Luxemburgo",
    "Cyprus"                 to "Chipre",
    "Belarus"                to "Bielorrusia",
    "Azerbaijan"             to "Azerbaiyán",
    "Montenegro"             to "Montenegro",
    "Albania"                to "Albania",
    "Moldova"                to "Moldavia",
    "Faroe Islands"          to "Islas Feroe",
    "Kosovo"                 to "Kosovo",
    "Gibraltar"              to "Gibraltar",
    "Malta"                  to "Malta",
    "Andorra"                to "Andorra",
    "San Marino"             to "San Marino",
    // América del Norte / Centro / Caribe
    "United States"          to "Estados Unidos",
    "Canada"                 to "Canadá",
    "Mexico"                 to "México",
    "Costa Rica"             to "Costa Rica",
    "Panama"                 to "Panamá",
    "Honduras"               to "Honduras",
    "Jamaica"                to "Jamaica",
    "El Salvador"            to "El Salvador",
    "Cuba"                   to "Cuba",
    "Trinidad and Tobago"    to "Trinidad y Tobago",
    "Haiti"                  to "Haití",
    "Curacao"                to "Curazao",
    "Guatemala"              to "Guatemala",
    // América del Sur
    "Brazil"                 to "Brasil",
    "Peru"                   to "Perú",
    "Paraguay"               to "Paraguay",
    "Venezuela"              to "Venezuela",
    "Ecuador"                to "Ecuador",
    "Bolivia"                to "Bolivia",
    // Oceanía
    "New Zealand"            to "Nueva Zelanda",
    "Australia"              to "Australia",
)

internal fun String.enEspañol(): String = NOMBRES_ES[this] ?: this
